services: # Services = containers that will run
  postgres: # PostgreSQL Database Service
    # Image to use from Docker Hub (postgres version 15)
    # Docker will automatically download this if not present
    image: postgres:latest

    # Custom name for the container (easier to identify)
    container_name: postgres-db

    # Restart policy: always restart if container stops
    restart: always

    # Environment variables passed to PostgreSQL container
    environment:
      # Database username - ${VAR} means read from .env file
      POSTGRES_USER: ${POSTGRES_USER}

      # Database password - NEVER hardcode, use .env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      # Database name to create on first run
      POSTGRES_DB: ${POSTGRES_DB}

    # Port mapping: host_port:container_port
    # 5432 is PostgreSQL default port
    # Left side (5432) = your computer's port
    # Right side (5432) = container's port
    ports:
      - "5432:5432"

    # Volumes = persistent storage (data survives container restart)
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

    # Networks allow containers to communicate
    # Containers in same network can talk to each other
    networks:
      - app-network

# Networks definition
networks:
  # Bridge network allows containers to communicate
  app-network:
    # Bridge = default Docker network type
    # Containers can reach each other by service name
    driver: bridge

# Volumes definition
volumes:
  # Named volume for PostgreSQL data
  # Docker manages where this is stored on your computer
  # Data persists even if you stop/remove containers
  postgres_data:
